# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_testing_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='text',
        ),
    ]
